### PR TITLE
Make functions returned "real" actions.

### PR DESCRIPTION
**Pull request by rwjblue**
This prevents the extra/double mutable object wrapping when passing down from one layer to the next (and avoids requiring extra `(action` wrapping to prevent this).

Given the following:

```hbs
{{! app/templates/route-template.hbs }}

{{parent-component go=(route-action 'foo')}}
```

```hbs
{{! app/templates/components/parent-component.hbs }}

{{child-component go=go}}
```

Prior to this change, `child-component` would get a mutable object in `this.attrs.go` instead of the invokable function (to work around this you would have to continue to wrap with `(action` either via `{{child-component go=(action go)}}` or `{{parent-component go=(action (route-action 'foo'))}}`).

After this change, `this.attrs.go()` Just Works™.

### CODE REVIEW

**Comment by poteto** [comment]
Excellent! LGTM

**Comment by rwjblue** [comment]
Looks like Travis finally finished all of @martndemus's jobs :stuck_out_tongue_closed_eyes:

**Comment by martndemus** [comment]
I'm sorry 🙃

**Comment by poteto** [comment]
@homu r+

**Pull request merged**
