### PR TITLE
Fix deprecation warning in Ember 2.13

### PR DESCRIPTION
**Pull request by topaxi**
See http://emberjs.com/deprecations/v2.x/#toc_ember-router-router-renamed-to-ember-router-_routermicrolib

### CODE REVIEW

**Comment by blimmer** [comment]
Now that 2.13 is live it would be great to get this deprecation warning silenced.

**Comment by poteto** [comment]
Let me figure out why the tests are failing on latest, beta, and canary...

**Comment by poteto** [comment]
Pending #56 to be merged with fix for failing test

**Comment by poteto** [comment]
Going to merge this for now and release a patch

**Pull request merged**
