### PR TITLE
First implementation of helper

### PR DESCRIPTION
**Pull request by poteto**

### CODE REVIEW

**Comment by poteto** [comment]
:eyes: please @rwjblue

**Comment by rwjblue** [comment]
:+1:

**Comment by rwjblue** [comment]
We should also add 2.0.0 and 2.1.0 to ember-try config.

**Comment by poteto** [comment]
Updated per comments @rwjblue!

**Comment by rwjblue** [comment]
@homu r+

**Comment by rwjblue** [comment]
@poteto - release at will :smile_cat:

**Pull request merged**
